#INCLUDE<P16F877A.INC>
	
ORG		0X00
COUNT		EQU  0X20
ADC		EQU  0X21
INPUT		EQU  0X22
REF		EQU  0X23
OUTPUT		EQU  0X24
GOTO		MAIN

MAIN
	;SELECT BANK 1 (01)
	BCF		STATUS,6	
	BSF		STATUS,5	;
	CLRF		TRISD		;PORTD IS CONFIGURED AS OUTPUT
	BSF		TRISA,0		;PORTA	IS CONFIGURED AS INPUT
	
	BCF		ADCON1,7 	;LEFT JUSTIFIED(0)
	
	BCF		ADCON1,3	;ANALOG (0001)
	BCF		ADCON1,2	
	BCF		ADCON1,1	
	BSF		ADCON1,0	
	
	;SELECT BANK 0(00)
	BCF		STATUS,5
	
	CLRF		PORTD		;PORTD IS CLEARED
	BSF		ADCON0,7	;SELECT CLOCK (Fosc/32)
	BCF		ADCON0,6 	
	

START
	;********START OF ADC*********
	BCF		STATUS,6	;SELECT BANK 0 (00)
	BCF		STATUS,5
	BCF		ADCON0,5	;CHANNEL SELECT (000)
	BCF		ADCON0,4
	BCF		ADCON0,3 	;channel 0
	BSF		ADCON0,0	;TURN ON ADC MODULE
	call		DELAY
	BSF		ADCON0,2	;START CIONVERSION
	LOOP1	
	BTFSC		ADCON0,2
	GOTO		LOOP1
	;********END OF ADC********
	
	MOVF		ADRESH,0
	MOVWF		INPUT		;MOVE W REGISTER VALUE TO ADC
	
	;MOVF		ADC,0		;ADC RESULT -> W REG
	;MOVWF		INPUT		;W REG -> INPUT1 ; INPUT1 = ADC_RESULT
	
	
	;********CHECKING THE INPUT********
	MOVLW D'6'			;CHECK ADC RESULT < 7
	MOVWF REF
	CALL COMPARE
	BTFSC OUTPUT,0		
	GOTO LESS_7			
	
	MOVLW D'12'			;CHECK ADC RESULT < 13
	MOVWF REF		
	CALL COMPARE
	BTFSC OUTPUT,0		
	GOTO LESS_13		
	
	MOVLW D'18'			;CHECK ADC_RESULT < 19
	MOVWF REF		
	CALL COMPARE
	BTFSC OUTPUT,0	
	GOTO LESS_19		
	
	MOVLW D'24'			;CHECK ADC RESULT < 25
	MOVWF REF		
	CALL COMPARE
	BTFSC OUTPUT,0		
	GOTO LESS_25		
	
	MOVLW D'30'			;CHECK ADC RESULT < 31
	MOVWF REF		
	CALL COMPARE
	BTFSC OUTPUT,0		
	GOTO LESS_31		
	
	MOVLW D'36'			;CHECK ADC RESULT < 37
	MOVWF REF		
	CALL COMPARE
	BTFSC OUTPUT,0		
	GOTO LESS_37		
	
	MOVLW D'42'			;CHECK ADC RESULT < 43
	MOVWF REF		
	CALL COMPARE
	BTFSC OUTPUT,0		
	GOTO LESS_43		
	
	MOVLW D'50'			;CHECK ADC RESULT < 51
	MOVWF REF		
	CALL COMPARE
	BTFSC OUTPUT,0	
	GOTO LESS_51
		
	CLRF PORTD
	GOTO START
LESS_7
	MOVLW B'10000000'
	MOVWF PORTD
	GOTO START
LESS_13
	MOVLW B'11000000'
	MOVWF PORTD
	GOTO START
LESS_19
	MOVLW B'11100000'
	MOVWF PORTD
	GOTO START
LESS_25
	MOVLW B'11110000'
	MOVWF PORTD
	GOTO START
LESS_31
	MOVLW B'11111000'
	MOVWF PORTD
	GOTO START
LESS_37
	MOVLW B'11111100'
	MOVWF PORTD
	GOTO START
LESS_43
	MOVLW B'11111110'
	MOVWF PORTD
	GOTO START

LESS_51
	MOVLW B'11111111'
	MOVWF PORTD
	GOTO START
		
;********SUBROUTINE FOR COMPARE TWO NUMBERS********
COMPARE
	MOVF	REF,0	    ;LOAD REF TO W REGISTER
	SUBWF	INPUT,0	    ;(INPUT - REF)
	
	BTFSC	STATUS,Z    ;IF INPUT=REF => Z=1 . ELSEIF INPUT><REF => Z=0
	GOTO	EQUAL	    ;IF Z=0 SKIP THIS INSTRUCTION
	
	BTFSC	STATUS,C    ;IF INPUT<REF => C=0 . ELSEIF INPUT>=REF => C=1 
	GOTO	GREATER	    ;IF C=0 SKIP THIS INSTRUCTION
	GOTO	LESS
	
	LESS
	MOVLW	B'00000001'
	MOVWF	OUTPUT
	BCF	STATUS,C
	GOTO	END_SUB
	
	EQUAL
	MOVLW	B'00000011'
	MOVWF	OUTPUT
	BCF	STATUS,C
	BCF	STATUS,Z
	GOTO	END_SUB
	
	GREATER
	MOVLW	B'00000010'
	MOVWF	OUTPUT
	GOTO	END_SUB
	
	END_SUB
RETURN
	
	
;**********20us DELAY********
DELAY
	BCF STATUS,6	;SELECT BANK 0 (00)
	BCF STATUS,5
	MOVLW 0X14
	MOVWF COUNT
LOOP
	DECFSZ COUNT,1
	GOTO LOOP
RETURN
	
END